### ISSUE TITLE
Start/Stop/Position not working since latest Update

### ISSUE THREAD

**Issue by michael-kaufmann** [maros/Zway-DeviceMove#1]
Hi,

I upgraded recently all zwave Components.
Firmware now is 2.2.3
U.I. is 1.4.3
Basemodule is 1.09
DeviceMove is 1.08

Since the upgrade the DeviceMove App is not working properly.
Im Using this App together with Roller Shutter FGRM-222.

Excample:
Status: Shutter is up:
Pressing Down-Key in virtual device, shutter moves down ==> OK
Now pressing Stopp-Key shutter turns and moves up again or shutter stops very shortly and then moves down again ==> WRONG
After that Virtual Device is not working vor several minutes.

Same behavior (vice versa) when shutter is down, 

Later: Setting a Position: Nothing happens.

Config of virtual shutter device:
{"data":{"instanceId":"0","moduleId":"DeviceMove","active":"true","title":"_Rollos APP - SUED ","params":{"devices":[{"device":"ZWayVDev_zway_11-0-38","timeUp":35,"timeDown":35}],"difference":10,"icon":"default","step":"1","report":"none","relatedCheck":false},"id":27,"creationTime":1476128477},"code":200,"message":"200 OK","error":null}

Log:
Attached
[log.txt](https://github.com/maros/Zway-DeviceMove/files/531976/log.txt)

**Comment by maros** [comment]
Thank you for the detailed bug report. This issue was fixed in release 1.09
